require('./bootstrap');
require('admin-lte');
require( 'datatables.net' );
require( 'datatables.net-bs4' );
require( 'datatables.net-fixedcolumns' );
require( 'datatables.net-fixedcolumns-bs4' );
require( 'datatables.net-buttons' );
require('./dataTable-editor.min');
require('./dataTables.checkboxes.min');
require( 'bootstrap-switch' );
require( 'select2' );
require('./index');
